export function randomPrompt() {
  return prompts[Math.floor(Math.random() * prompts.length)];
}

const prompts = [
  "What makes you feel most alive?",
  "What is one belief you changed your mind about?",
  "What does courage look like in everyday life?",
  "Is it better to be born good, or to overcome your evil nature?",
  "What is the best advice you have ever received?",
  "Is failure necessary for success?",
  "What makes a good friend?",
  "Should people spend more time alone?",
  "What is one thing schools should teach but do not?",
  "Is technology making us more connected or more lonely?",
  "What does success mean to you?",
  "Should everyone keep a journal?",
  "What is something small that can change someone’s day?",
  "Is honesty always the best policy?",
  "What makes a place feel like home?",
  "Should people follow their passion or be practical?",
  "What is one habit worth building?",
  "Is competition good for people?",
  "What does it mean to be mature?",
  "Should phones be allowed in classrooms?",
  "What is one thing you wish more people understood?",
  "Is it better to be respected or liked?",
  "What makes a leader trustworthy?",
  "Should everyone learn public speaking?",
  "What role does luck play in success?",
  "What is the value of boredom?",
  "Should people read more fiction?",
  "What is one lesson you learned the hard way?",
  "Is money a good measure of success?",
  "What makes a conversation meaningful?",
  "Should people take more risks?",
  "What is one thing you would teach your younger self?",
  "Are first impressions reliable?",
  "What does kindness cost?",
  "Should everyone have a creative hobby?",
  "What makes a team work well?",
  "Is change something to fear or welcome?",
  "What is the most useful life skill?",
  "Should people care what others think?",
  "What does freedom mean to you?",
  "Is social media good for society?",
  "What makes someone interesting?",
  "Should people travel more?",
  "What is one problem your generation must solve?",
  "Is it better to know a little about many things or a lot about one thing?",
  "What does confidence look like?",
  "Should people forgive easily?",
  "What is the difference between being busy and being productive?",
  "Is it important to have role models?",
  "What makes a promise meaningful?",
  "Should everyone learn a second language?",
  "What is one tradition worth keeping?",
  "Is comfort overrated?",
  "What makes a person wise?",
  "Should people spend less time online?",
  "What is one thing that always makes you curious?",
  "Is it better to plan carefully or improvise?",
  "What does responsibility mean?",
  "Should animals have more legal protection?",
  "What makes a story powerful?",
  "Is patience still important in a fast world?",
  "What is one fear worth facing?",
  "Should people be judged by their intentions or actions?",
  "What does it mean to live well?",
  "Is popularity valuable?",
  "What makes a memory last?",
  "Should students choose what they study?",
  "What is one invention you could not live without?",
  "Is teamwork always better than working alone?",
  "What does loyalty mean?",
  "Should people talk to strangers more often?",
  "What is one thing adults often forget?",
  "Is there such a thing as too much ambition?",
  "What makes a mistake useful?",
  "Should everyone volunteer?",
  "What does happiness depend on?",
  "Is talent more important than effort?",
  "What is one rule you would change?",
  "Should people argue more or less?",
  "What makes someone brave?",
  "Is privacy still possible today?",
  "What is one thing nature can teach us?",
  "Should children have more freedom?",
  "What does it mean to be original?",
  "Is it better to be optimistic or realistic?",
  "What makes a job meaningful?",
  "Should people be more direct?",
  "What is one skill you want to master?",
  "Is silence sometimes better than speaking?",
  "What does justice mean to you?",
  "Should everyone learn basic first aid?",
  "What is one thing that should never be rushed?",
  "Is nostalgia helpful or harmful?",
  "What makes a city great?",
  "Should people celebrate small wins?",
  "What is one thing you would do if you had no fear?",
  "Is it better to ask for permission or forgiveness?",
  "What does generosity look like?",
  "Should people spend more time outdoors?",
  "What makes a good apology?",
  "Is discipline more important than motivation?",
  "What is one question everyone should ask themselves?",
  "Should we value speed or quality more?",
  "What makes a person easy to trust?",
  "Is it okay to quit?",
  "What is one thing that deserves more attention?",
  "Should people learn to be comfortable with uncertainty?",
  "What does friendship require?",
  "Is intelligence overrated?",
  "What makes a goal worth pursuing?",
  "Should people keep secrets?",
  "What is one thing you would change about modern life?",
  "Is humor important in serious situations?",
  "What makes a community strong?",
  "Should everyone learn how to manage money?",
  "What does it mean to be generous with your time?",
  "Is it better to fit in or stand out?",
  "What is one lesson sports can teach?",
  "Should people be rewarded for effort or results?",
  "What makes a teacher memorable?",
  "Is perfection worth chasing?",
  "What is one thing that gives you hope?",
  "Should people take more breaks?",
  "What does it mean to listen well?",
  "Is it better to have many options or fewer choices?",
  "What makes a home welcoming?",
  "Should everyone experience living in another place?",
  "What is one thing that should be easier?",
  "Is curiosity more important than knowledge?",
  "What makes a challenge exciting?",
  "Should people share their goals publicly?",
  "What does it mean to be fair?",
  "Is confidence learned or natural?",
  "What is one thing worth waiting for?",
  "What makes a celebration meaningful?",
  "Is routine helpful or limiting?",
  "What is one object that tells a story about you?",
  "Should people spend money on experiences or things?",
  "What does respect look like in disagreement?",
  "What makes a decision difficult?",
  "What is one habit that improves relationships?",
  "Is fear ever useful?",
  "What makes a person influential?",
  "Should people know their neighbors?",
  "What is one thing society takes for granted?",
  "Is it better to be kind or truthful?",
  "What makes a day well spent?",
  "Should students get homework?",
  "What does creativity mean?",
  "Is hard work always rewarded?",
  "What is one thing you wish you could do again for the first time?",
  "Should people disconnect from technology regularly?",
  "What makes a place beautiful?",
  "Is it better to lead or support?",
  "What is one thing that can unite people?",
  "Should people learn from history?",
  "What does being healthy really mean?",
  "Is it important to have dreams that seem unrealistic?",
  "What makes a person dependable?",
  "Should people challenge traditions?",
  "What is one question you hate being asked?",
  "Is winning important?",
  "What makes a good rule?",
  "Should people be more playful?",
  "What is one thing you would preserve for the future?",
  "What does peace mean to you?",
  "Should everyone learn how to build something?",
  "What is one thing that changes with age?",
  "Is it better to apologize quickly or thoughtfully?",
  "What makes someone a good listener?",
  "Should people spend more time with older generations?",
  "What is one belief people should question more?",
  "Is rest productive?",
  "What makes a gift meaningful?",
  "What is one thing you would make free for everyone?",
  "Is it better to be consistent or flexible?",
  "What makes a person memorable?",
  "Should people learn how to handle criticism?",
  "What is one thing you admire in others?",
  "Is being busy a status symbol?",
  "What makes a family strong?",
  "Should everyone try performing on stage once?",
  "What is one thing that makes life simpler?",
  "Is it better to solve problems alone or with others?",
  "What makes a place worth visiting?",
  "Should people take promises more seriously?",
  "What is one thing you would never automate?",
  "What makes a person feel heard?",
  "What is one thing the future will judge us for?",
  "Is it better to have a plan or a purpose?",
  "What makes an ordinary moment special?",
  "Should people spend more time asking questions?",
] as const;
